build-backend-code-job:
  stage: build
  only:
 #   changes:
 #     - backend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - cd backend
    - mvn package
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
pachca-notification-backend:
  stage: notify
#  only:
#   changes:
#     - backend/*
#   variables:
#     - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - 'curl -X POST -H "Content-type: application/json" --data
      "{\"message\":\"Всё ещё что-то собираем. Ссылка на артефакт: https://gitlab.praktikum-services.ru/api/v4/projects/2012/jobs/artifacts/release-0.0.1/download?job=build-backend-code-job\"}"
      "https://api.pachca.com/webhooks/01GHKAEEBHC027DJAH7CHPTVF1"'
  needs:
    - build-backend-code-job
