build-backend-code-job:
  stage: build
  only:
    changes:
      - backend/*
    variables:
      - $CI_COMMIT_MESSAGE =~ /send notification/
  script:
    - cd backend
    - mvn package "-Dmaven.repo.local=${CI_PROJECT_DIR}/.m2/repository"
    
  artifacts:
    paths:
      - backend/target/sausage-store-0.0.1-SNAPSHOT.jar
      - ${CI_PROJECT_DIR}/.m2/ # сохранение зависимостей для SAST 
spotbugs-sast:
  stage: test
  needs:
    - build-backend-code-job
  variables:
    COMPILE: "false"
    SAST_JAVA_VERSION: 16
    MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository # не забудьте при сборке также указывать эту папку через аргумент -Dmaven.repo.local
  artifacts:
    reports:
      sast: gl-sast-report.json

sonarqube-backend-sast:
  stage: test
  needs:
    - build-backend-code-job
  image: maven:3.8-openjdk-16 # тот самый docker-образ, о котором мы все узнаем в будущем
  script:
    - cd backend
    - >
      mvn verify sonar:sonar -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_BACKEND_KEY}
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_BACKEND}
      -Dsonar.projectName=${SONAR_PROJECT_BACKEND_NAME}
      
            
pachca-notification-backend:
  stage: notify
  script:
    - 'curl -X POST -H "Content-type: application/json" --data
      "{\"message\":\"Всё ещё что-то собираем. Ссылка на артефакт: https://gitlab.praktikum-services.ru/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=build-backend-code-job\"}"
      "https://api.pachca.com/webhooks/01GHKAEEBHC027DJAH7CHPTVF1"'
  needs:
    - sonarqube-backend-sast

