build-frontend-code-job:
  stage: build
  rules:
    - if: $CI_COMMIT_MESSAGE =~ /send notification/


  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

sonar-scanner:
  stage: test
  needs:
    - build-frontend-code-job
  image:
    name: sonarsource/sonar-scanner-cli:latest
  script:
    - cd frontend
    - >
      sonar-scanner -Dsonar.qualitygate.wait=true
      -Dsonar.projectKey=${SONAR_PROJECT_FRONTEND_KEY}
      -Dsonar.sources=. 
      -Dsonar.host.url=${SONARQUBE_URL}
      -Dsonar.login=${SONAR_LOGIN_FRONTEND}
      
    

pachca-notification-frontend:
  stage: notify
  script:
    - 'curl -X POST -H "Content-type: application/json" --data
      "{\"message\":\"Кто-то продолжает что-то собирать. Ссылка на артефакт: https://gitlab.praktikum-services.ru/api/v4/projects/$CI_PROJECT_ID/jobs/artifacts/$CI_DEFAULT_BRANCH/download?job=build-frontend-code-job\"}"
      "https://api.pachca.com/webhooks/01GHKAEEBHC027DJAH7CHPTVF1"'
  needs:
    - sonar-scanner
