build-frontend-code-job:
  stage: build
  only:
    changes:
      - frontend/*
  script:
    - cd frontend
    - npm install
    - npm run build
  artifacts:
    paths:
      - frontend/dist/frontend

pachca-notification-frontend:
  stage: notify
  only:
    changes:
      - frontend/*
  script:
    - 'curl -X POST -H "Content-type: application/json" --data
      "{\"message\":\"Савин Александр собрал фронт.\"}"
      "https://api.pachca.com/webhooks/01GHKAEEBHC027DJAH7CHPTVF1"'
  needs:
    - build-frontend-code-job