include:
- local: "/.backend-ci.yml"
- local: "/.frontend-ci.yml"
- template: Security/SAST.gitlab-ci.yml
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  MAVEN_REPO_PATH: ${CI_PROJECT_DIR}/.m2/repository
stages:
- build
- test
- release
- notify

