include:
- local: "/backend/.gitlab-ci.yml"
- local: "/frontend/.gitlab-ci.yml"
- template: Security/SAST.gitlab-ci.yml
variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
stages:
- build
- test
- release
- notify

