version: "3.3"

services:
  backend-green: &backend
    container_name: backend-green
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend:latest
    env_file: ./backend/backend.env
    restart: always
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: "backend"
    networks:
      - sausage_network
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6 
  backend-blue:
    container_name: backend-blue
    <<: *backend
    #image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend:latest
    #env_file: ./backend/backend.env
    #restart: always
    #environment:
    #  SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    # VIRTUAL_HOST: "backend"
    #networks:
    #  - sausage_network
    #healthcheck:
    #  test: curl --fail -s http://localhost:8080/actuator/health
    #  interval: 30s
    #  timeout: 10s
    #  retries: 6 
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend-report:latest
    env_file: 
      - ./backend-report/backend-report.env
    restart: always
    ports:
      - "8888:8888"
    networks:
      - sausage_network
  frontend:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-frontend:latest
    env_file:
      - ./frontend/frontend.env
    ports:
      - "1080:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    environment:
      DEFAULT_HOST: "backend"
    container_name: frontend
    networks:
      - sausage_network 

networks:
  sausage_network:
          
