version: "3.3"

services:
  backend-green: &backend
    container_name: backend-green
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend:latest
    env_file: ./backend/backend.env
    restart: always
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
      VIRTUAL_HOST: "backend"
    networks:
      - sausage_network
    healthcheck:
      test: curl --fail -s http://localhost:8080/actuator/health
      interval: 30s
      timeout: 10s
      retries: 6 
  backend-blue:
    container_name: backend-blue
    <<: *backend
  backend-report:
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend-report:latest
    env_file: 
      - ./backend-report/backend-report.env
    restart: always
    ports:
      - "8888:8888"
    networks:
      - sausage_network
  frontend:
    restart: always
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-frontend:latest
    ports:
      - "80:80"
    container_name: frontend
    networks:
      - sausage_network 

networks:
  sausage_network:
          
