variables:
  VERSION: 1.0.${CI_PIPELINE_ID}
  JAVA_OPTS: -XX:MaxRAMPercentage=90
include:
  - project: templates/ci
    file: DockerInDockerTemplate.yml
stages:
  - test
  - deploy

python_test_job:
  stage: test
  image: python:latest
  variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
  cache:
    paths:
      - .cache/pip
  before_script:
    - cd backend-report
    - >
    - pip install -r requirements.txt --upgrade pip
    - pip3 install requests python-dotenv unittest2
  script:
    - python3 -m unittest

deploy-backend-report:
  stage: deploy
  image: vault:1.11.3
  before_script:
    - apk add openssh-client bash
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - export VAULT_TOKEN="$(vault write -field=token auth/jwt/login role=sausage-store jwt=$CI_JOB_JWT)"      
    - ssh ${DEV_USER}@${DEV_HOST}
      "export "VERSION=${VERSION}";
      export "SPRING_DATA_MONGODB_URI=$(vault kv get -field=spring.data.mongodb.uri secret/sausage-store)";
      export "GITLAB_REGISTRY=${GITLAB_REGISTRY}";
      export "PY_MONGO_PORT=${PY_MONGO_PORT}";
      export "GITLAB_USER=${GITLAB_USER}";
      export "GITLAB_PASS=${GITLAB_PASS}";
      export "GIT_FOLDER=${GIT_FOLDER}";
      /bin/bash -s " < ./backend-report/backend-report-deploy.sh
