version: "3.3"

services:
  backend:
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-backend:latest
    container_name: sausage-store-backend
    env_file: ./backend/.backend-env
    restart: always
    environment:
      SPRING_FLYWAY_BASELINE-ON-MIGRATE: "true"
    networks:
      - sausage_network
  backend-report:
    build:
     context: ./backend-report/
     dockerfile: Dockerfile
    container_name: sausage-store-backend-report
    environment:
      DB: mongodb://std-013-60:Testusr1234@rc1a-xb6q7pmw36t77ryz.mdb.yandexcloud.net:27018/std-013-60?tls=true
    networks:
      - sausage_network
  frontend:
    image: gitlab.praktikum-services.ru:5050/std-013-60/sausage-store/sausage-frontend:latest
    container_name: sausage-store-frontend
    ports:
      - "1080:80"
    networks:
      - sausage_network

networks:
  sausage_network: 
